name: pug
description: A starting point for Dart libraries or applications.
version: 0.0.3
homepage: https://www.github.com/thecodechef/dart_pug
repository: https://www.github.com/thecodechef/dart_pug
author: Jeremy Bolding <cyberchefjay@gmail.com.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

excutables:
  pug: null

dependencies:
  analyzer: ^0.36.0
  args: ^1.5.1
  collection: ^1.14.11
  crypto: ^2.0.6
  html: ^0.14.0+1
  http_parser: ^3.1.3
  logging: ^0.11.3+2
  markdown: ^2.0.2
  mustache: ^1.1.1
  process:  ^3.0.9
  package_config: ^1.0.5
  path: ^1.6.2
  pub_semver: ^1.4.2
  quiver: ^2.0.3
  resource: ^2.1.5
  stack_trace: ^1.9.3
  yaml: ^2.1.15

dev_dependencies:
  build: any
  build_runner: any
  build_version: any
  coverage: any
  dhttpd: any
  glob: any
  grinder: any
  io: any
  http: any
  meta: any
  pedantic: any
  test: any
